// Generated by Tools/install_vehicle_sprites.py — do not edit by hand.
//
// Where each silhouette's ink sits inside the shared sprite canvas, as
// fractions of the image height. The set is cropped to one box so the
// vehicles keep their relative sizes, which leaves the shorter ones with
// empty air above them. Anything that wants the CAR centred rather than
// the IMAGE centred needs these.

import Foundation

public enum VehicleSpriteMetrics {
    /// Height over width of the shared sprite canvas.
    public static let canvasAspect: Double = 0.7976

    /// (top, bottom) of the drawn area, 0 = image top.
    public static func inkBounds(style: String) -> (top: Double, bottom: Double) {
        switch style {
        case "bicycle": return (0.0065, 0.9925)
        case "car": return (0.2785, 0.9925)
        case "convertible": return (0.3183, 0.9935)
        case "crossover": return (0.0140, 0.9925)
        case "hatchback": return (0.2914, 0.9925)
        case "motorcycle": return (0.0946, 0.9925)
        case "pickup": return (0.2581, 0.9925)
        case "scooter": return (0.0430, 0.9935)
        case "sports": return (0.3097, 0.9925)
        case "van": return (0.0258, 0.9935)
        default: return (0.0, 1.0)
        }
    }

    /// The tallest silhouette's share of the image height.
    ///
    /// Lists pin their plates to this so rows keep one height. Sizing
    /// each plate to its own vehicle is right for a hero and wrong for a
    /// list, where a garage of a saloon and a crossover would step.
    public static let tallestInk: Double = 0.9860

    /// How much of the image height the vehicle actually occupies.
    public static func inkHeight(style: String) -> Double {
        let b = inkBounds(style: style)
        return max(0.05, b.bottom - b.top)
    }

    /// Offset, in image heights, that moves the ink's centre onto the
    /// image's centre. Positive means «shift the image up».
    public static func centeringOffset(style: String) -> Double {
        let b = inkBounds(style: style)
        return ((b.top + b.bottom) / 2) - 0.5
    }
}
