#!/usr/bin/env python3
"""Install the style x colour vehicle matrix into both asset catalogs.

Both, not one: the Live Activity is a separate target with its own catalog, and
a sprite present in the app but missing from the extension shows up as a blank
avatar on the Lock Screen and nowhere else — the quietest kind of bug there is.
`VehicleAvatarCatalogTests` fails the build when the two drift, and this script
is the thing that keeps them from drifting in the first place.
"""
import glob, json, os, shutil, sys
from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOGS = [
    os.path.join(REPO, "TripTrack/Resources/Assets.xcassets"),
    os.path.join(REPO, "TripTrackLiveActivity/Assets.xcassets"),
]
# Largest render is the vehicle-detail hero at 64 pt; 256 px covers it at 3x
# with room for a bigger layout without shipping 1254 px of unseen detail.
LONGEST = 256

CONTENTS = {
    "images": [
        {"filename": None, "idiom": "universal", "scale": "1x"},
        {"idiom": "universal", "scale": "2x"},
        {"idiom": "universal", "scale": "3x"},
    ],
    "info": {"author": "xcode", "version": 1},
}


def set_bbox(srcs):
    """One bounding box for the whole set.

    Cropping each sprite to its own subject would make a hatchback and a van
    the same size on screen — and the proportions are exactly what tells the
    silhouettes apart. Cropping them all to the SAME box removes the shared
    empty margin (27% of the canvas height, which is why the cars looked small
    in their tiles) while leaving every relative difference intact.
    """
    import numpy as np
    x0 = y0 = 10 ** 9
    x1 = y1 = 0
    for f in srcs:
        a = np.array(Image.open(f).convert("RGBA"))
        ys, xs = np.where(a[:, :, 3] > 16)
        if len(xs) == 0:
            continue
        x0, x1 = min(x0, xs.min()), max(x1, xs.max())
        y0, y1 = min(y0, ys.min()), max(y1, ys.max())
    pad = 6
    return (max(0, x0 - pad), max(0, y0 - pad), x1 + 1 + pad, y1 + 1 + pad)


def install(src, catalogs=CATALOGS, longest=LONGEST, box=None):
    name = os.path.splitext(os.path.basename(src))[0]
    im = Image.open(src).convert("RGBA")
    if box:
        im = im.crop(box)
    if max(im.size) > longest:
        im.thumbnail((longest, longest), Image.LANCZOS)
    written = 0
    for catalog in catalogs:
        imageset = os.path.join(catalog, f"{name}.imageset")
        os.makedirs(imageset, exist_ok=True)
        png = os.path.join(imageset, f"{name}.png")
        im.save(png, optimize=True)
        c = json.loads(json.dumps(CONTENTS))
        c["images"][0]["filename"] = f"{name}.png"
        with open(os.path.join(imageset, "Contents.json"), "w") as f:
            json.dump(c, f, indent=2)
            f.write("\n")
        written += os.path.getsize(png)
    return name, im.size, written


def prune(keep, catalogs=CATALOGS):
    """Remove pixel_* imagesets no longer in the matrix, so a silhouette that
    was dropped does not linger as dead weight in two targets."""
    removed = []
    for catalog in catalogs:
        for d in glob.glob(os.path.join(catalog, "pixel_*.imageset")):
            n = os.path.basename(d)[: -len(".imageset")]
            if n not in keep:
                shutil.rmtree(d)
                removed.append(n)
    return sorted(set(removed))


def write_metrics(srcs, box):
    """Emit where each silhouette's ink actually sits inside the shared canvas.

    The whole set is cropped to ONE box so a van stays taller than a hatchback,
    which means every shorter silhouette carries empty air above it — 27% of the
    height for a saloon against 1% for a crossover. A view that centres the
    IMAGE therefore hangs the car off the bottom of its plate with a hole on
    top, which is exactly what the vehicle screen did.

    Generated rather than hand-written: these numbers change the moment a sprite
    is redrawn, and a stale table is a layout bug nobody would think to look for.
    """
    import numpy as np
    rows = {}
    for f in srcs:
        name = os.path.splitext(os.path.basename(f))[0]
        style = name[len("pixel_"):].rsplit("_", 1)[0]
        if style in rows:
            continue
        a = np.array(Image.open(f).convert("RGBA").crop(box))
        ys, _ = np.where(a[:, :, 3] > 16)
        h = a.shape[0]
        rows[style] = (ys.min() / h, (ys.max() + 1) / h)

    lines = [
        "// Generated by Tools/install_vehicle_sprites.py — do not edit by hand.",
        "//",
        "// Where each silhouette's ink sits inside the shared sprite canvas, as",
        "// fractions of the image height. The set is cropped to one box so the",
        "// vehicles keep their relative sizes, which leaves the shorter ones with",
        "// empty air above them. Anything that wants the CAR centred rather than",
        "// the IMAGE centred needs these.",
        "",
        "import Foundation",
        "",
        "public enum VehicleSpriteMetrics {",
        "    /// Height over width of the shared sprite canvas.",
        f"    public static let canvasAspect: Double = {(box[3]-box[1]) / (box[2]-box[0]):.4f}",
        "",
        "    /// (top, bottom) of the drawn area, 0 = image top.",
        "    public static func inkBounds(style: String) -> (top: Double, bottom: Double) {",
        "        switch style {",
    ]
    for style in sorted(rows):
        t, b = rows[style]
        lines.append(f'        case "{style}": return ({t:.4f}, {b:.4f})')
    lines += [
        "        default: return (0.0, 1.0)",
        "        }",
        "    }",
        "",
        "    /// The tallest silhouette's share of the image height.",
        "    ///",
        "    /// Lists pin their plates to this so rows keep one height. Sizing",
        "    /// each plate to its own vehicle is right for a hero and wrong for a",
        "    /// list, where a garage of a saloon and a crossover would step.",
        f"    public static let tallestInk: Double = {max(b - t for t, b in rows.values()):.4f}",
        "",
        "    /// How much of the image height the vehicle actually occupies.",
        "    public static func inkHeight(style: String) -> Double {",
        "        let b = inkBounds(style: style)",
        "        return max(0.05, b.bottom - b.top)",
        "    }",
        "",
        "    /// Offset, in image heights, that moves the ink's centre onto the",
        "    /// image's centre. Positive means «shift the image up».",
        "    public static func centeringOffset(style: String) -> Double {",
        "        let b = inkBounds(style: style)",
        "        return ((b.top + b.bottom) / 2) - 0.5",
        "    }",
        "}",
        "",
    ]
    dst = os.path.join(REPO, "TripTrackShared", "VehicleSpriteMetrics.swift")
    with open(dst, "w") as fh:
        fh.write("\n".join(lines))
    print(f"metrics for {len(rows)} silhouettes -> {os.path.relpath(dst, REPO)}")


if __name__ == "__main__":
    srcdir = sys.argv[1]
    srcs = sorted(glob.glob(os.path.join(srcdir, "pixel_*.png")))
    if not srcs:
        sys.exit(f"no pixel_*.png in {srcdir}")
    box = set_bbox(srcs)
    print(f"set bbox {box[2]-box[0]}x{box[3]-box[1]} from {Image.open(srcs[0]).size[0]} px canvas")
    keep, total = set(), 0
    for s in srcs:
        name, size, written = install(s, box=box)
        keep.add(name)
        total += written
    # Prune only on an explicit flag. Pruning by default deletes every sprite
    # that is not in the batch being installed — which is correct when the
    # batch IS the whole matrix and destructive the moment somebody installs
    # one style on its own, as happened the first time this ran.
    write_metrics(srcs, box)
    gone = prune(keep) if "--prune" in sys.argv else []
    print(f"installed {len(keep)} sprites x 2 catalogs at {LONGEST} px — {total//1024} KB total")
    if gone:
        print(f"pruned {len(gone)}: {', '.join(gone)}")
